### PR TITLE
Upgrade GHC to 8.10.4

### LINKED ISSUE #30: build and test with ghc-8.8 and stack
FYI, f1be137fe99588e39f17336dcf8f693b662acf41

```
PATH=/opt/ghc/ghc-8.8.4/bin:$PATH stack --resolver=lts-16.15 test
...
All 108 tests passed (1.39s)
music-suite> Test suite music-suite-test-laws passed
...
UTMS export done
  Number of errors: 20
music-suite> Test suite music-suite-test-umts passed
...
All 126 tests passed (0.18s)

music-suite> Test suite music-suite-test-xml-parser passed
```
It seems that `stack` insists on build all executables (before running tests).
With `ghc-options: -fno-code` , it will  fail on installing the executables,
and run no tests.

### LINKED ISSUE #33: [with ghc-8.10] Couldn't match type ‘Item (LabelTree BracketType Staff)’ with ‘Staff’
```
PATH=/opt/ghc/ghc-8.10.2/bin:$PATH stack --resolver=nightly-2020-09-24 test
...

[124 of 129] Compiling Music.Score.Export.StandardNotation
            
....../music-suite/src/Music/Score/Export/StandardNotation.hs:868:48: error:
    • Couldn't match type ‘Item (LabelTree BracketType Staff)’
                     with ‘Staff’
      Expected type: [Staff]
        Actual type: [Item (LabelTree BracketType Staff)]
    • In the second argument of ‘($)’, namely ‘toList st’
      In the expression: fmap (length . _bars) $ toList st
      In a pattern binding:
        numBars :: [Int] = fmap (length . _bars) $ toList st
    |       
868 |     numBars :: [Int] = fmap (length . _bars) $ toList st
    |                                                ^^^^^^^^^
```
it's strange that it works with ghc-8.8.

### LINKED ISSUE #44: XML export fails for provided examples
Steps to reproduce:

- Compile package as per README instructions.
- Compile one of the examples, e.g.:

```
m> cabal exec -- ghc -package music-suite --make examples/chopin.hs 
```

- Try exporting to a MusicXML file:

```
m> ./examples/chopin -f xml -o chopin.musicxml
  Simplifying pitches
  Extracting parts
    Done, 1 parts
  Merging overlapping notes into chords
  Separating voices
  Notating dynamics, articulation and playing techniques
  Dividing the score into bars
  Rewriting rhythms
  Generate staff groups
  System staff bars: 7
  Regular staff bars: [7,6]
  MusicXML: Assuming one movement only
  MusicXML: Extracting title and composer
  MusicXML: Generating part list
  MusicXML: Generating bar content
    MusicXML: Generating staff <<>>
    MusicXML: Generating staff <<>>
chopin: (+): no method for Index n. Sorry.
CallStack (from HasCallStack):
  error, called at src/TypeUnary/Nat.hs:300:16 in type-unary-0.3.2-39ddeecb212e2916c7fa88277634b57b2e10b14889d4d6f88f468109dd1faf22:TypeUnary.Nat
m> 
```

### PR DESCRIPTION
**Pull request by hanshoglund**
Upgrade GHC to 8.10.4. This patch was created using the "Upgrade" instructions in the README.

Fixes #30 
Fixes #33 
Fixes #44 (no reproduce)

### CODE REVIEW

**Comment by cianoc** [comment]
I built this in a fresh cabal and all the tests were successful. However the default version that ghcup will download will be 8.10.5, which won't work with this branch. As it stands a user won't be able to install music-suite following the instructions, so I think the readme needs to be updated (I'm happy to do that as either part of this pull request, or as a new pull request). These instructions will:
- State the version that is required to build the latest version of music-suite (8.10.4).
- Tell the user _how_ to download it using ghcup (it's not terribly obvious).

In addition another change that I think would be helpful for cabal users would be to modify the project.cabal file so that it has the following line:
`
with-ghc: 8.10.4
`
That way cabal will build with the right version (so long as it's been installed), without the user having to activate anything.

**Comment by hanshoglund** [comment]
@cianoc I've added the `ghc-version` field. Will merge once the CI is happy.

Do you think you make a separate PR adding instructions for Cabal to the README?

**Comment by cianoc** [comment]
Yes I would be very happy to add those instructions to the README.
