### ISSUE TITLE
[with ghc-8.10] Couldn't match type ‘Item (LabelTree BracketType Staff)’ with ‘Staff’

### ISSUE THREAD

**Issue by jwaldmann** [music-suite/music-suite#33]
```
PATH=/opt/ghc/ghc-8.10.2/bin:$PATH stack --resolver=nightly-2020-09-24 test
...

[124 of 129] Compiling Music.Score.Export.StandardNotation
            
....../music-suite/src/Music/Score/Export/StandardNotation.hs:868:48: error:
    • Couldn't match type ‘Item (LabelTree BracketType Staff)’
                     with ‘Staff’
      Expected type: [Staff]
        Actual type: [Item (LabelTree BracketType Staff)]
    • In the second argument of ‘($)’, namely ‘toList st’
      In the expression: fmap (length . _bars) $ toList st
      In a pattern binding:
        numBars :: [Int] = fmap (length . _bars) $ toList st
    |       
868 |     numBars :: [Int] = fmap (length . _bars) $ toList st
    |                                                ^^^^^^^^^
```
it's strange that it works with ghc-8.8.

**Comment by jwaldmann** [comment]
Perhaps some change in GHC's deriving mechanism? Since `toList st`, and  this `st` is last component of `Movement`, and 
```
data Movement
  = Movement
      { _movementInfo :: MovementInfo,
        _systemStaff :: SystemStaff,
        -- Don't allow names for staff groups, only staves
        _staves :: LabelTree BracketType Staff
      }

data LabelTree b a = Branch b [LabelTree b a] | Leaf a
  deriving (Functor, Foldable, Traversable, ..
```

**Comment by jwaldmann** [comment]
But no, `Item` is a type family (cf. https://hackage.haskell.org/package/base-4.14.0.0/docs/GHC-Exts.html#t:IsList) and the compiler should have resolved `Item (LabelTree BracketType Staff)`? But I am not seeing any `instance IsList (LabelTree ..)`. Again - why does this work with ghc-8.8?

**Comment by jwaldmann** [comment]
The reason is a change in base-prelude from 1.3  to 1.4
https://github.com/nikita-volkov/base-prelude/commit/cb9fcaed9091525afb252953ce77038574cd9ccb

which we pick up because of nightly/lts-16
https://www.stackage.org/lts-16.15/package/base-prelude-1.3

**Comment by hanshoglund** [comment]
Hi @jwaldmann. 

Currently the only supported way of building Music Suite is the way described in the README (which uses Nix to pin versions of GHC and all dependencies). I wouldn't object to a PR adding support for a Stack build, as long as it:

- Uses the same version of GHC and all dependencies as the Nix build (or includes changes to the the code, making it compatible with both setups).
- Includes PR a CI setup, allowing the new build config to be automatically tested.

**Comment by jwaldmann** [comment]
I'll look into it. Yes, reproducible builds (by pinned version) and CI is important.

**Comment by cianoc** [comment]
I have stack working with resolver: lts-16.31
which seemed to be the closest to the NIX build. 

The only problem I run into is I have to remove the ghc-options for the executables. Which is annoying, but doesn't make a huge difference to compile time in practice. I think this may be a stack bug/issue unfortunately.

Would a CI have to do anything more than just run 'stack build'?

**Comment by hanshoglund** [comment]
Hello @cianoc

The CI should probably run `stack test` and `stack haddock` (to make sure PRs don't accidentally break the doc strings).

To be clear I would prefer that the Cabal build continues to work, and that both versions use the same dependencies. I can think of ways of making this possible, but sadly none of them are trivial (generating Cabal freeze file from Stack YAML files, or vice versa, or check in both with a script to prevent them from going out of sync, etc). I'm open to proposals for how to make this work smoothly.

Note that it is also possible to use Cabal without Nix (for example by installing via [ghcup](https://www.haskell.org/ghcup/)). If this is a viable option for you, maybe you would be interested in contributing a (non-Nix) CI config for Cabal, or documentation for this workflow.

**Comment by cianoc** [comment]
The Cabal process as described in the readme did not work for me. I was able to get stack working. If there's a way to get it working without using stack I'd be happy to do that, otherwise I guess I can look into trying to get cabal to work.

**Comment by cianoc** [comment]
The error message in case this is helpful:
`Warning: Requested index-state 2020-04-24T15:14:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2020-04-24T15:12:45Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: music-suite-2.0.0 (user goal)
[__1] next goal: base (dependency of music-suite)
[__1] rejecting: base-4.12.0.0/installed-4.12.0.0, base-4.12.0.0,
base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0,
base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2,
base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0,
base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0,
base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0,
base-3.0.3.2, base-3.0.3.1 (constraint from project config TODO requires
==4.13.0.0)
[__1] fail (backjumping, conflict set: base, music-suite)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, music-suite
`

Having had a brief look at it this seems to be because the cabal freeze file is out of sync with the current version of ghc available on ghc-cup (8.8.4, whereas it's looking for 8.8.3). I guess the freeze file needs to be updated? But I think unless you're prepared to update the cabal freeze file every time there's a point release of ghc - supporting cabal in this way doesn't seem very sustainable.

**Comment by hanshoglund** [comment]
See also further discussion on #54.

PR #55 adds support for building with GHC 8.10.4, which should be available from ghcup.
